name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create time tag
        run: |
          echo "time=$(date '+%Y%m%d%H%M')" >> $GITHUB_ENV
          echo dherkyan/cin-news-links:${{env.time}}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context:
          push: true
          tags: dherkyan/cin-news-links:${{env.time}}

      - name: Checkout no reposti√≥rio (argocd-deploy-apps-cin-news-links-k8s)
        uses: actions/checkout@v4
        with:
          repository: 'softwarefoundation/argocd-deploy-apps-cin-links-k8s'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Atualizando arquivo de deployment do app (cin-news-links)
        run: |
          git config user.email dherkyan@gmail.com
          git config user.name 'Automation Deployment Argo CD'
          pwd
          cat k8s/deployment.yaml
          sed -i "s+dherkyan/cin-news-links.*+dherkyan/cin-news-links:${{env.time}}+g" k8s/deployment.yaml
          cat k8s/deployment.yaml
          git add .
          git commit -m '[Bot] Automation Deployment Argo CD: Deploy imagem dherkyan/cin-news-links:${{env.time}}'
          git push origin main
